name 'ifserver-neos'
maintainer 'Interfrog Produktion GmbH'
maintainer_email 'm.albers@division.ag'
license 'MIT'
description 'Loads typo3 neos specific nginx config'
version '1.0.2'
depends 'nginx, composer'
